require('plugins')
require('plugins.packer')
require('settings')
require('setup')
require('keymaps')
require('setup.lualine')
require('setup.telescope')
-- require('setup.ayu')
require('setup.nightfox')
require('setup.autopairs')
require('setup.whichkey')
require('setup.nvim-tree')
require('setup.treesitter')
require('setup.lsp')
require('setup.cmp')
require('setup.gitsigns')
require('setup.toggleterm')
require('setup.spectre')
-- require('setup.gutentags')
